/*-----------------------------------------
                  DOCUMENT ABOUT INTERRUPT IN STM32F103 - DETAILS IN MANUAL RM0008
1.NVIC (Nest Vectored Interrupt Controller:
  - The Nested Vectored Interrupt Controller (NVIC) is a specialized peripheral in ARM Cortex-M microcontrollers,
like the STM32F1 series, that manages interrupts.  Its purpose is to control the prioritization and handling of 
interrupts efficiently, allowing complex systems to respond to critical events while maintaining smooth program execution.
  - Purpose: 
            +, Interrput management
            +, Priotity Setting
            +, Interrupt Nesting
            +, Vectoring to ISRs: 

2. Vector table:
  - The vector table in ARM Cortex-M microcontrollers is a memory structure that maps each interrupt
and exception to a specific address in memory, pointing to the Interrupt Service Routine (ISR) that
will handle each one. The NVIC uses this vector table to quickly locate and execute the correct ISR
whenever an interrupt or exception occurs.
  - Location of vector table: 
  - Structure of the Vector table:
  - Access by  NVIC

3. ISR: Interrupt service routine (IRQHandler - it is a suffix)
  - An Interrupt Service Routine (ISR) is a special function that executes in response to an interrupt request
ISRs are a crucial part of embedded systems, enabling the processor to respond to real-time events,
such as external signals or internal system events, with minimal delay.
  - Characteristic of an ISR:
                  +, Asynchronous executin
                  +, No return value
                  +, Minimal execution time
                  +, Directly associated with an interrupt: Each ISR is mapped to a specific interrupt vector in the vector table
                  +, Special registers for context switch
  - Steps in ISR execution:
                  +, Interrupt occurrence
                  +, Interrupt acknowledgment
                  +, Context saving
                  +, Jump to ISR address
                  +, ISR execution
                  +, Interrupt flag clearing
                  +, Return and context restore

4. Interrupt in STM32:
  - Two way: external interrupt(GPIO) and internal interrupt(UART, SPI, I2C)
a, External interrupt: 
  - External interrupts are triggered by events from external sources, such as hardware buttons,
sensors, or other devices interfacing with the microcontroller.
  - Implement steps:
                +, Configure the external pin
                +, Configure the interrupt
                +, Enable the interrupt
                +, Write the ISR
                +, NVIC configuration: 
b, Internal interrupt
  - Internal interrupts are triggered by events within the microcontroller, such as those generated
by peripherals like UART, SPI, I2C, timers, or ADCs.
  - Implement steps:    
                +, Configure the peripherals
                +, Enable interrupt in the peripherals
                +, Write the ISR
                +, NVIC configuration

5. IRQ: interrupt request
  - IRQ stands for Interrupt Request. It is a signal sent to the processor (microcontroller or CPU) 
indicating that an event needs immediate attention. When an IRQ is generated, it interrupts the normal
flow of execution, allowing the processor to handle the event, typically by executing an Interrupt Service Routine (ISR).
  - external IRQ and internal IRQ.
  - Characteristic of IRQ:
          +, Type of IRQ
          +, IRQ number: each interrupt source has a unique IRQ number.This number is used to identify which interrupt occurred and to determine which ISR to execute.
          +, Priority
          +, Interrupt vector table: the processor uses an Interrupt Vector Table (IVT) to determine the ISR associated with each IRQ number.
          +, Pending and active IRQs.

---> Note: Each IRQ number maps to a specific ISR defined in the interrupt vector table. When an interrupt occurs, the NVIC uses the IRQ number to look up the address
of the corresponding ISR in the vector table.

---------------------------------------- NVIC registers ---------------------------------------------
1. ISER: interrupt set-enable register 
2. ICER: interrupt clear-enable register
3. ISPR: Interrupt  set-pending register
4. ICPR: Interrupt clear-pending register
5. IABR: Interrupt active bit register
6. IPR: Interrupt priority register
7. STIR: Software trigger interrupt register

---------------------------------------- EXTI register ----------------------------------------------
1. Definition
  - The EXTI (External Interrupt/Event Controller) registers on the STM32F103 microcontroller are used
to configure and control external interrupts generated by GPIO pins.
2. Registers
a, EXTI_IMR: Interrupt mask register: Each bit corresponds to an external interrupt line. If a bit is set to 1, the corresponding external interrupt line is enabled.
b, EXTI_EMR: Similar to the Interrupt Mask Register, but this register is used to configure the EXTI lines to generate events instead of interrupts.
c, EXTI_RTSR: This register configures which EXTI lines will trigger on a rising edge (transition from low to high)
d, EXTI_FTSR: This register configures which EXTI lines will trigger on a falling edge (transition from high to low).
E, EXTI_PR: This register indicates which EXTI lines are pending an interrupt. It shows which interrupt lines have been triggered and are waiting to be serviced.
and To clear a pending interrupt, you must write a 1 to the corresponding bit.





















*/